
name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Yeh step GitHub ko 'app' folder mein le jaye ga
      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Build APK
        run: flutter build apk --release
        working-directory: app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: star-chat-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
